### PR TITLE
Fix chappress deploy

### PR DESCRIPTION
**Pull request by spence-man**
Fix ChapPress Capistrano deploy script and upgrade Wordpress core version, plugins & theme.

Story: https://trello.com/c/vAGPb2HZ

Made some minor edits in `/config` & `/devops/ansible` directories. The last couple commits are solely for the WordPress Updates.

### CODE REVIEW

**Review by kaydanzie — APPROVED** [review]
Looks good to me. As long as the other developers approve and can run the cap staging deploy command, you have my approval. Once they submit their approval in GitHub you are free to merge this PR and wrap up the story.

**Comment by spence-man** [comment]
@kaylaziegler Ok sounds good. I'll write another comment with instructions for setting up the keys.

**Comment by spence-man** [comment]
@cbryant24, @khafa100 

The chappress server, https://chappress-staging.chapman.edu, will need your public authentication key if you guys would like to ssh into chapress-staging or run `cap staging deploy`.

On your local machine, run:
    
    ssh-copy-id deploy@chappress-staging.chapman.edu

Your public key should be transfered over. As long as your keys are located in `~/.ssh/`. See this [article](https://www.ssh.com/ssh/copy-id) if otherwise.

After this, test out ssh:

    ssh deploy@chappress-staging.chapman.edu

Or for deploying:
    
    cap staging deploy

**Comment by khafa100** [comment]
@spence-man `ssh-copy-id` worked fine for me, but I'm asked for the password so I'm unable to deploy or ssh. Would you mind sharing the password with me in a temporary google doc?

Actually, is the `ssh-copy-id` supposed to be `deploy@chappress-staging.chapman.edu`? Or is it still `deploy@blogs-staging.chapman.edu`?

**Comment by spence-man** [comment]
@khafa100 Oh oops, looks like I put the wrong server for my previous comment. I just fixed that.
Yea, it's supposed to be 

    ssh-copy-id deploy@chappress-staging.chapman.edu

After this you shouldn't need the deploy password. It should bypass asking for it.

**Comment by khafa100** [comment]
@spence-man I think I still need the password for the initial `ssh-copy-id` unless I'm doing something wrong?

```
$ ssh-copy-id deploy@chappress-staging.chapman.edu
/usr/local/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/Users/khafa100/.ssh/id_rsa.pub"
/usr/local/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/local/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
deploy@chappress-staging.chapman.edu's password: 
```
Or do I need to overwrite my current rsa key with the instructions in the article you linked?

**Comment by spence-man** [comment]
@khafa100 Right, sorry. Just sent the google docs. Let me know how it goes.

**Comment by khafa100** [comment]
@spence-man Thanks! Unfortunately, I received `Permission denied` when I entered the password for `ssh-copy-id deploy@chappress-staging.chapman.edu`.

**Comment by spence-man** [comment]
@khafa100  Ok, let me take a look. I don't see your key in `/home/deploy/.ssh/authorized_keys`. That's what that command is supposed to do. Let me try something and comment again soon.

**Comment by spence-man** [comment]
@khafa100 Ok hopefully this works. I manually added your and Chris' keys to the authorized keys file. You can try to ssh or deploy now.

**Comment by khafa100** [comment]
@spence-man Both `ssh` and `cap staging deploy` worked for me! I'm not sure why it didn't take my password entry before. Maybe I needed to manually type it in, instead of copy-paste.

**Review by khafa100 — APPROVED** [review]

**Comment by spence-man** [comment]
@khafa100 Ok great, thanks for testing that out. Yea, I'm not sure either why the password entry didn't work. I think the same thing happened for Kayla. Fixed it by manually adding her key as well.

**Review by cbryant24 — APPROVED** [review]

**Pull request merged**
