### PR TITLE
[DEFECT] Reorganize ansible

### PR DESCRIPTION
**Pull request by spence-man**
Encountered various PHP configuration issues using the [geerling.php role](https://galaxy.ansible.com/geerlingguy/php/). It works with on a local setup using the [wimops guide](https://wimops.chapman.edu/wiki/VirtualBox#Red_Hat_Virtual_Machine_Setup). However, the staging site has not been tested.I was able to clear up some issues and get the Ansible script running on Redhat VM. I don’t have any current pending issues from the VM. But I haven’t tried the staging yet. I didn’t want to cause any issues and leave the site broken.  Since the staging is already configured I’m not sure if there will be any conflicts with the new Ansible config for nginx,php,etc. A clean snapshot could test whether it goes well or not.  

The `/devops/ansible` code needs a full review to abide by this [trello story](https://trello.com/c/9Miy21xL). 

Possible Steps:

- Code review
- Save the current snapshot on the staging server
- Run a clean snapshot on the staging server (IS&T)
- Run Ansible script on staging site
- Run Capistrano to install latest WordPress repo from Github
- Verify Wordpress works and install runs flawlessly  

Solved issues encountered:
- Added package to `__php_packages` variable in `geerlingguy.php/vars/redhat` template. Initially failed to find and install `php-mysql` in yum repo 
- Added `--enable-fpm` in php_source_configure_command variable in geerlingguy.php/defaults/main.yml 
- In server template, changed php block from `fastcgi_pass  unix:/run/php-fpm/www.sock;` to `fastcgi_pass  127.0.0.1:9000;`. Listen socket/port for php-fpm(fastcgi_param) not configured properly between Nginx & PHP
  - /devops/ansible/roles/basic-packages/templates
  - geerling.php & geerling.nginx
- Visiting local site, index.php gets downloaded due to php not configured properly in template. Issue related to previous fix.
- WP Permission issues for deploy user solved by adding basic-package as last role to be deployed
- Redirect from http to https solved by adding `nginx_redirect` variables to host_vars

### CODE REVIEW

**Review by tatwell — COMMENTED** [review]
This looks ok to me. Much of it is going to be taken up in the coming Blogs Virtualbox story, so I didn't scrutinize it too closely.

One question: did you change any of the roles themselves? Your comments gave me the impression you did. If so, can you point out where you did with comments? I would like to review those.

**Comment by spence-man** [comment]
Yes, the roles seemed to work after I added these two parts:
- chap-press/devops/ansible/roles/geerlingguy.php/vars/RedHat.yml

Added: `- php-mysql`
To: `__php_packages:`

- chap-press/devops/ansible/roles/geerlingguy.php/defaults/main.yml

Added `--enable-fpm`
To: `php_source_configure_command:`

I tried to avoid editing the roles themselves and adding them to group vars or host_var. But for whatever reason when I added these parts to the role directly the install worked. There might be a better way to include those variables.

**Comment by tatwell** [comment]
@spence-man Yes, it would be preferable not to edit the roles themselves but it looks like in this case it had to be done. The main concern is that the role packages get updated, overwriting our edits, and the playbook suddenly breaks. 

We can revisit this in the Blogs VirtualBox story if necessary.

**Comment by spence-man** [comment]
This PR is updated with Ansible galaxy roles that are imported. No edits are made to these directly and any variables or configurations are set in the vars directories.

The structure of Ansible was reformatted and fixed in the Blogs repo. This repo was updated with those changes and any variables with `blogs.chapman.edu` were replaced with `chapress-staging.chapman.edu`. Any previous comments or errors were solved with the reformat. Ansible is  operational and this PR will be merged to reflect those changes.

**Pull request merged**
